---
apiVersion: v2
appVersion: v0.23.0
description: Autobrr monitors IRC announce channels to get releases as soon as they are available with good filtering
name: autobrr
version: 1.1.2
kubeVersion: ">=1.16.0-0"
keywords:
  - autobrr
  - torrrent
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/autobrr
icon: https://avatars.githubusercontent.com/u/88781313?s=200&v=4
sources:
  - https://github.com/autobrr/autobrr
  - https://github.com/k8s-at-home/container-images
maintainers:
  - name: funkypenguin
    email: davidy@funkypenguin.co.nz
dependencies:
  - name: common
    repository: oci://ghcr.io/geek-cookbook/elf-charts
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
