{{ if .Values.webdavplus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: webdav-plus
  labels:
    app.kubernetes.io/name: webdavplus
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:    
  - port: 5574
    targetPort: 5574
    protocol: TCP
    name: webdavplus
  selector:
    app.kubernetes.io/name: webdavplus
    app.kubernetes.io/instance: {{ .Release.Name }}
