---
apiVersion: v2
appVersion: 0.0.1
description: Manage media posters
name: plex-meta-manager
version: 2.4.4
kubeVersion: ">=1.16.0-0"
keywords:
  - komga
  - comics
  - mangas
  - server
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/komga
icon: https://komga.org/assets/media/logo.svg
sources:
  - https://komga.org/
  - https://github.com/gotson/komga
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
dependencies:
  - name: common
    repository: http://chartmuseum.chartmuseum:8080
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
