{{ if .Values.premiumize.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rclone-{{ .Release.Name }}-premiumize
  labels:
    name: rclone-{{ .Release.Name }}-premiumize
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi # doesn't matter, is used to match with the PVC
  storageClassName: rclone
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: csi-rclone
    volumeHandle: rclone-{{ .Release.Name }}-premiumize
    volumeAttributes:
      secretName: "{{ .Release.Name }}-premiumize"
{{ end }}