---
apiVersion: v2
appVersion: version-v0.5.3
description: Mylar is the automated Comic Book downloader (cbr/cbz) for use with various download clients.
name: mylar
version: 4.4.2
kubeVersion: ">=1.16.0-0"
keywords:
  - mylar
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/mylar
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/mylar-icon.png
sources:
  - https://github.com/mylar3/mylar3
  - https://github.com/linuxserver/docker-mylar3
  - https://github.com/k8s-at-home/charts/tree/master/charts/mylar
maintainers:
  - name: Patricol
    url: https://patricol.co/
dependencies:
  - name: common
    repository: http://chartmuseum.chartmuseum:8080
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
