---
apiVersion: v2
appVersion: 1.27.0
description: Alternative implementation of the Bitwarden server API in Rust, including the Web Vault
name: webhook-receiver
version: 0.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - webhook-receiver
home: https://github.com/dani-garcia/webhook-receiver
sources:
  - https://github.com/dani-garcia/webhook-receiver
maintainers:
  - name: funkypenguin
    email: davidy@funkypenguin.co.nz
dependencies:
  - name: common
    repository: oci://ghcr.io/geek-cookbook/elf-charts
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
