---
apiVersion: v2
appVersion: 2.6.0
description: Server error pages in the docker image
name: error-pages
version: 1.2.2
kubeVersion: ">=1.16.0-0"
keywords:
  - traefik
  - error-pages
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/error-pages
icon: https://hsto.org/webt/rm/9y/ww/rm9ywwx3gjv9agwkcmllhsuyo7k.png
sources:
  - https://github.com/tarampampam/error-pages
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: http://chartmuseum.chartmuseum:8080
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
