---
apiVersion: v2
appVersion: 4.1.2
description: pyLoad is a Free and Open Source download manager written in Python and designed to be extremely lightweight, easily extensible and fully manageable via web.
name: rclonebrowser
version: 0.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - shoko
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/pyload
icon: https://avatars.githubusercontent.com/u/3521496?s=200&v=4
sources:
  - https://github.com/ShokoAnime/ShokoServer
  - https://hub.docker.com/r/shokoanime/server
maintainers:
  - name: funkypenguin
    email: davidy@funkypenguin.co.nz
dependencies:
  - name: common
    repository: oci://ghcr.io/geek-cookbook/elf-charts
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
