---
apiVersion: v2
appVersion: 2.18.0
description: filebrowser provides a file managing interface within a specified directory
name: filebrowser
version: 1.4.2
kubeVersion: ">=1.16.0-0"
keywords:
  - filebrowser
home: https://github.com/k8s-at-home/charts/tree/master/charts/incubator/filebrowser
icon: https://raw.githubusercontent.com/filebrowser/logo/master/icon.png
sources:
  - https://github.com/filebrowser/filebrowser
maintainers:
  - name: PixelJonas
    email: 5434875+PixelJonas@users.noreply.github.com
dependencies:
  - name: common
    repository: oci://ghcr.io/geek-cookbook/elf-charts
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
