---
apiVersion: v2
appVersion: v1.0.0.2255
description: Looks and smells like Sonarr but made for music
name: lidarr
version: 14.2.2
kubeVersion: ">=1.16.0-0"
keywords:
  - lidarr
  - torrent
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/lidarr
icon: https://github.com/lidarr/Lidarr/blob/develop/Logo/512.png?raw=true
sources:
  - https://github.com/Lidarr/Lidarr
  - https://github.com/k8s-at-home/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: http://chartmuseum.chartmuseum:8080
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
