---
apiVersion: v2
appVersion: v3.14.2
description: Usenet meta search
name: nzbhydra2
version: 10.4.2
kubeVersion: ">=1.16.0-0"
keywords:
  - nzbhydra2
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/nzbhydra2
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hydra-icon.png
sources:
  - https://github.com/theotherp/nzbhydra2
  - https://github.com/k8s-at-home/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: http://chartmuseum.chartmuseum:8080
    version: ~0.2.5
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
