---
apiVersion: v2
appVersion: v3.3.1
description: Free and easy binary newsreader
name: sabnzbd
version: 9.4.3
kubeVersion: ">=1.16.0-0"
keywords:
  - sabnzbd
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/sabnzbd
icon: https://avatars1.githubusercontent.com/u/960698?s=400&v=4
sources:
  - https://sabnzbd.org/
  - https://github.com/k8s-at-home/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: http://chartmuseum.chartmuseum:8080
    version: ~0.2.5
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
