{{ if .Values.homepage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  kubernetes.yaml: |
    mode: cluster  

  settings.yaml: |
    title: {{.Release.Name}}'s ElfHosted Services
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80

  layout:
    - Links:
        style: row
    - Consume Media:
    - Manage Media:
    - Manage Downloads:

  services.yaml: |
    - Consume Media:

        {{ if .Values.jellyfin.enabled }}
        - Jellyfin:
            icon: jellyfin.png
            href: https://{{ .Release.Name }}-jellyfin.elfhosted.com
            description: Stream Media
            widget:
              type: jellyfin
              url: http://jellyfin:8096
              key: {{`{{HOMEPAGE_VAR_JELLYFIN_KEY}}`}} 
        {{ end }} 

        {{ if or .Values.plex.enabled .Values.plexgluetun.enabled .Values.plexpia.enabled }}
        - Plex:
            icon: plex.png
            href: https://{{ .Release.Name }}-plex.elfhosted.com
            description: Stream Media
            widget:
              type: plex
              url: http://plex:32400
              key: {{`{{HOMEPAGE_VAR_PLEX_KEY}}`}} 
        {{ end }}

        {{ if .Values.emby.enabled }}
        - Emby:
            icon: emby.png
            href: https://{{ .Release.Name }}-emby.elfhosted.com
            description: Stream Media
            widget:
              type: jellyfin
              url: http://emby:8096
              key: {{`{{HOMEPAGE_VAR_EMBY_KEY}}`}} 
        {{ end }} 
        
        {{ if .Values.navidrome.enabled }}
        - Navidrome:
            icon: navidrome.png
            href: https://{{ .Release.Name }}-navidrome.elfhosted.com
            description: Stream Music
            widget:
              type: navidrome
              url: http://navidrome:4533
              user: {{`{{HOMEPAGE_VAR_NAVIDROME_USER}}`}} 
              token: {{`{{HOMEPAGE_VAR_NAVIDROME_TOKEN}}`}} 
              salt: {{`{{HOMEPAGE_VAR_NAVIDROME_SALT}}`}} 
        {{ end }}      

        {{ if .Values.calibreweb.enabled }}
        - Calibre Web:
            icon: calibre-web.png
            href: https://{{ .Release.Name }}-calibre-web.elfhosted.com
            description: Consume eBooks
            widget:
              type: calibreweb
              url: http://calibreweb:8083
              username: {{`{{HOMEPAGE_VAR_CALIBREWEB_USERNAME}}`}} 
              password: {{`{{HOMEPAGE_VAR_CALIBREWEB_PASSWORDN}}`}} 
        {{ end }}
        
        {{ if .Values.calibre.enabled }}
        - Calibre:
            icon: calibre.png
            href: https://{{ .Release.Name }}-calibre.elfhosted.com
            description: Manage eBooks
        {{ end }}             
                      
        {{ if .Values.komga.enabled }}
        - Komga:
            icon: komga.png
            href: https://{{ .Release.Name }}-komga.elfhosted.com
            description: Manage Comics
            widget:
              type: komga
              url: http://komga:25600
              username: {{`{{HOMEPAGE_VAR_KOMGA_USERNAME}}`}} 
              password: {{`{{HOMEPAGE_VAR_KOMGA_PASSWORD}}`}}            
        {{ end }}   

        {{ if .Values.kavita.enabled }}
        - Kavita:
            icon: kavita.png
            href: https://{{ .Release.Name }}-kavita.elfhosted.com
            description: Manage Comics / Books
            widget:
              type: kavita
              url: http://komga:5000
              username: {{`{{HOMEPAGE_VAR_KAVITA_USERNAME}}`}} 
              password: {{`{{HOMEPAGE_VAR_KAVITA_PASSWORD}}`}}            
        {{ end }}     

        {{ if .Values.audiobookshelf.enabled }}
        - Audio Bookshelf:
            icon: audiobookshelf.png
            href: https://{{ .Release.Name }}-audiobookshelf.elfhosted.com
            description: Consume Audio Books / Podcasts
            widget:
              type: audiobookshelf
              url: http://audiobookshelf:8000
              key: {{`{{HOMEPAGE_VAR_AUDIOBOOKSHELF_KEY}}`}}            
        {{ end }}                 

    - Manage Media:
        {{ if .Values.radarr.enabled }}
        - Radarr:
            icon: radarr.png
            href: https://{{ .Release.Name }}-radarr.elfhosted.com
            description: Manage Movies
            widget:
              type: radarr
              url: http://radarr:7878
              key: {{ .Values.radarrexposed.apikey }}
        {{ end }}  

        {{ if .Values.radarr4k.enabled }}
        - Radarr 4K:
            icon: radarr.png
            href: https://{{ .Release.Name }}-radarr4k.elfhosted.com
            description: Manage 4K Movies
            widget:
              type: radarr
              url: http://radarr4k:7878
              key: {{ .Values.radarr4kexposed.apikey }}
        {{ end }}              

        {{ if .Values.sonarr.enabled }}
        - Sonarr:
            icon: sonarr.png
            href: https://{{ .Release.Name }}-sonarr.elfhosted.com
            description: Manage Series
            widget:
              type: sonarr
              url: http://sonarr:8989
              key: {{ .Values.sonarrexposed.apikey }}
        {{ end }}  

        {{ if .Values.sonarr4k.enabled }}
        - Sonarr 4K:
            icon: sonarr.png
            href: https://{{ .Release.Name }}-sonarr4k.elfhosted.com
            description: Manage 4K Series
            widget:
              type: sonarr
              url: http://sonarr4k:8989
              key: {{ .Values.sonarr4kexposed.apikey }}
        {{ end }}   

        {{ if .Values.lidarr.enabled }}
        - Lidarr:
            icon: lidarr.png
            href: https://{{ .Release.Name }}-lidarr.elfhosted.com
            description: Manage Music
            widget:
              type: lidarr
              url: http://lidarr:8686
              key: {{ .Values.lidarrexposed.apikey }}
        {{ end }}   

        {{ if .Values.readarr.enabled }}
        - Readarr:
            icon: readarr.png
            href: https://{{ .Release.Name }}-readarr.elfhosted.com
            description: Manage eBooks
            widget:
              type: readarr
              url: http://readarr:8787
              key: {{ .Values.readarrexposed.apikey }}     
        {{ end }}             

        {{ if .Values.readarraudio.enabled }}
        - Readarr Audio:
            icon: readarr.png
            href: https://{{ .Release.Name }}-readarraudio.elfhosted.com
            description: Manage AudioBooks
            widget:
              type: readarr
              url: http://readarraudio:8787
              key: {{ .Values.readarraudioexposed.apikey }}     
        {{ end }}      

        {{ if .Values.lazylibrarian.enabled }}
        - Lazy Librarian:
            icon: lazylibrarian.png
            href: https://{{ .Release.Name }}-lazylibrarian.elfhosted.com
            description: Manage eBooks  
        {{ end }}  

        {{ if .Values.bazarr.enabled }}
        - Bazarr:
            icon: bazarr.png
            href: https://{{ .Release.Name }}-bazarr.elfhosted.com
            description: Manage Subtitles
            widget:
              type: bazarr
              url: http://bazarr:6767
              key: {{ .Values.bazarrexposed.apikey }}        
        {{ end }}  

        {{ if .Values.bazarr4k.enabled }}
        - Bazarr 4K:
            icon: bazarr.png
            href: https://{{ .Release.Name }}-bazarr4k.elfhosted.com
            description: Manage Subtitles (4K)
            widget:
              type: bazarr
              url: http://bazarr4k:6767
              key: {{ .Values.bazarr4kexposed.apikey }}         
        {{ end }}   

        {{ if .Values.mylar.enabled }}
        - Mylar:
            icon: mylar3.png
            href: https://{{ .Release.Name }}-mylar.elfhosted.com
            description: Manage Comics
            widget:
              type: mylar3
              url: http://mylar:8090
              key: {{ .Values.mylarrexposed.apikey }}     
        {{ end }}    

        {{ if .Values.rpdb.enabled }}
        - RPDB:
            icon: rpdb.png
            href: https://{{ .Release.Name }}-rpdb.elfhosted.com
            description: Manage Rating Posters      
        {{ end }}   

        {{ if .Values.ombi.enabled }}
        - Ombi:
            icon: ombi.png
            href: https://{{ .Release.Name }}-ombi.elfhosted.com
            description: Manage Requests     
            widget:
              type: ombi
              url: http://ombi:5000
              key: {{`{{HOMEPAGE_VAR_OMBI_KEY}}`}}       
        {{ end }}    

        {{ if .Values.overseerr.enabled }}
        - Overseerr:
            icon: overseerr.png
            href: https://{{ .Release.Name }}-overseerr.elfhosted.com
            description: Manage Requests     
            widget:
              type: overseerr
              url: http://overseerr:5055
              key: {{`{{HOMEPAGE_VAR_OVERSEERR_KEY}}`}}       
        {{ end }}        

        {{ if .Values.jellyseerr.enabled }}
        - Jellyseerr:
            icon: jellyseerr.png
            href: https://{{ .Release.Name }}-jellyseerr.elfhosted.com
            description: Manage Requests     
            widget:
              type: jellyseerr
              url: http://jellyseerr:5055
              key: {{`{{HOMEPAGE_VAR_JELLYSEERR_KEY}}`}}       
        {{ end }}       

        {{ if .Values.jfa.enabled }}
        - Jellyfin Accounts:
            icon: jfa.png
            href: https://{{ .Release.Name }}-jfa.elfhosted.com
            description: Manage Jellyfin Accounts         
        {{ end }}      

        {{ if .Values.tautulli.enabled }}
        - Tautulli:
            icon: tautulli.png
            href: https://{{ .Release.Name }}-tautulli.elfhosted.com
            description: Plex Statistics    
            widget:
              type: tautulli
              url: http://tautulli:8181
              key: {{`{{HOMEPAGE_VAR_TAUTULLI_KEY}}`}}       
        {{ end }}   

        {{ if .Values.xteve.enabled }}
        - Xteve:
            icon: xteve.png
            href: https://{{ .Release.Name }}-xteve.elfhosted.com
            description: Live TV Proxy for Plex/Emby    
            widget:
              type: xteve
              url: http://xteve:34400
              username: {{`{{HOMEPAGE_VAR_XTEVE_USERNAME}}`}} 
              password: {{`{{HOMEPAGE_VAR_XTEVE_PASSWORD}}`}}                 
        {{ end }}   

        {{ if .Values.nextpvr.enabled }}
        - NextPVR:
            icon: nextpvr.png
            href: https://{{ .Release.Name }}-nextpvr.elfhosted.com
            description: Live TV Proxy                    
        {{ end }}   

        {{ if .Values.notifiarr.enabled }}
        - Notifiarr:
            icon: notifiarr.png
            href: https://{{ .Release.Name }}-notifiarr.elfhosted.com
            description: Manage Discord-based Notifications                 
        {{ end }}   

        {{ if .Values.shoko.enabled }}
        - Shoko:
            icon: shoko.png
            href: https://{{ .Release.Name }}-shoko.elfhosted.com
            description: Manage Anime         
        {{ end }}      

        {{ if .Values.filebot.enabled }}
        - Filebot:
            icon: filebot.png
            href: https://{{ .Release.Name }}-filebot.elfhosted.com
            description: Automate Media Management         
        {{ end }}        

        {{ if .Values.unpackerr.enabled }}
        - Unpackerr:
            icon: unpackerr.png
            href: https://{{ .Release.Name }}-filebrowser.elfhosted.com/files/config/unpackerr/
            description: Automatically Unpack Media        
        {{ end }}       

        {{ if .Values.plexmetamanager.enabled }}
        - Plex Meta Manager:
            icon: plexmetamanager.png
            href: https://{{ .Release.Name }}-plexmetamanager.elfhosted.com
            description: Manage Plex Metadata     
        {{ end }}                      

        {{ if .Values.tdarr.enabled }}
        - Tdarr:
            icon: tdarr.png
            href: https://{{ .Release.Name }}-tdarr.elfhosted.com
            description: Automate Media Transcoding  
            widget:
              type: tdarr
              url: http://tdarr:8265
        {{ end }}   

    - Manage Downloads:
        {{ if .Values.nzbget.enabled }}
        - NZBGet:
            icon: nzbget.png
            href: https://{{ .Release.Name }}-nzbget.elfhosted.com
            description: Usenet Client  
            widget:
              type: nzbget
              url: http://nzbget:6789
        {{ end }}   

        {{ if .Values.sabnzbd.enabled }}
        - SABnzbd:
            icon: sabnzbd.png
            href: https://{{ .Release.Name }}-sabnzbd.elfhosted.com
            description: Usenet Client  
            widget:
              type: sabnzbd
              url: http://sabnzbd:8080
              {{ .Values.sabnzbdexposed.apikey }} 
        {{ end }}
        
        {{ if .Values.prowlarr.enabled }}
        - Prowlarr:
            icon: prowlarr.png
            href: https://{{ .Release.Name }}-prowlarr.elfhosted.com
            description: Manage Indexers  
            widget:
              type: prowlarr
              url: http://prowlarr:9696
              {{ .Values.prowlarrexposed.apikey }} 
        {{ end }}  

        {{ if .Values.nzbhydra.enabled }}
        - NZBHydra:
            icon: nzbhydra.png
            href: https://{{ .Release.Name }}-nzbhydra.elfhosted.com
            description: Manage Indexers
        {{ end }}           

        {{ if .Values.autobrr.enabled }}
        - Autobrr:
            icon: autobrr.png
            href: https://{{ .Release.Name }}-autobrr.elfhosted.com
            description: Manage torrent automation 
            widget:
              type: autobrr
              url: http://autobrr:7474
              key: {{`{{HOMEPAGE_VAR_AUTOBRR_KEY}}`}}       
        {{ end }}   

        {{ if or .Values.delugepia.enabled .Values.delugegluetun.enabled }}
        - Deluge:
            icon: deluge.png
            href: https://{{ .Release.Name }}-deluge.elfhosted.com
            description: Bittorrent Client
            widget:
              type: deluge
              url: http://deluge:8112
              password: deluge  
        {{ end }}   

        {{ if or .Values.qbittorrentpia.enabled .Values.qbittorrentgluetun.enabled }}
        - qBittorrent:
            icon: qbittorrent.png
            href: https://{{ .Release.Name }}-qbittorrent.elfhosted.com
            description: Bittorrent Client
            widget:
              type: qbittorrent
              url: http://qbittorrent:8000
        {{ end }}                   

        {{ if or .Values.rutorrentpia.enabled .Values.rutorrentgluetun.enabled }}
        - ruTorrent:
            icon: rutorrent.png
            href: https://{{ .Release.Name }}-rutorrent.elfhosted.com
            description: Bittorrent Client
            widget:
              type: rutorrent
              url: http://rutorrent:8080
        {{ end }}  

        {{ if .Values.pyload.enabled }}
        - pyLoad:
            icon: pyload.png
            href: https://{{ .Release.Name }}-pyload.elfhosted.com
            description: Manage downloads
            widget:
              type: pyload
              url: http://pyload:8000
        {{ end }}          

        {{ if .Values.youtubedl.enabled }}
        - YouTubeDL:
            icon: youtubedl.png
            href: https://{{ .Release.Name }}-youtubedl.elfhosted.com
            description: Manage YouTube Downloads
        {{ end }}  

        {{ if .Values.rapidleech.enabled }}
        - RapidLeech:
            icon: rapidleech.png
            href: https://{{ .Release.Name }}-rapidleech.elfhosted.com
            description: Rapidly Leech
        {{ end }}      

        {{ if .Values.rdtclient.enabled }}
        - RDT Client:
            icon: rdtclient.png
            href: https://{{ .Release.Name }}-rdtclient.elfhosted.com
            description: Manage real debrid(-like) services
        {{ end }}     

        {{ if .Values.openbooks.enabled }}
        - OpenBooks:
            icon: openbooks.png
            href: https://{{ .Release.Name }}-openbooks.elfhosted.com
            description: Manage eBooks Downloads
        {{ end }}      

        {{ if .Values.jdownloader.enabled }}
        - jDownloader:
            icon: jdownloader.png
            href: https://{{ .Release.Name }}-jdownloader.elfhosted.com
            description: Manage Downloads
            widget:
              type: jdownloader
              username: {{ .Values.jdownloader.MYJDOWNLOADER_EMAIL | default }}
              password: {{ .Values.jdownloader.MYJDOWNLOADER_PASSWORD | default }}
              client: {{ .Release.Name }}.elfhosted.com
        {{ end }}                                 

  widgets.yaml: |


    - greeting:
        text_size: 2xl
        text: üßù ElfHosted 

    - resources:
        label: /storage/elfstorage
        disk: /storage/elfstorage

  {{ if .Values.storageboxa.enabled }}
    - resources:
        label: /storage/storagebox-a
        disk: /storage/storagebox-a
  {{ end }}

  {{ if .Values.storageboxb.enabled }}
    - resources:
        label: /storage/storagebox-b
        disk: /storage/storagebox-b
  {{ end }}

  {{ if .Values.storageboxc.enabled }}
    - resources:
        label: /storage/storagebox-c
        disk: /storage/storagebox-c
  {{ end }}  

  bookmarks.yaml: |
    - Links:
        - Health:
            - abbr: GA
              href: "https://{{ .Release.Name }}-health.elfhosted.com"
              icon: gatus.png
        - Account:
            - abbr: GA
              href: "https://store.elfhosted.com/my-account/subscriptions/"
              icon: store.png              

        - Discord:
            - abbr: DI
              href: https://discord.elfhosted.com
              icon: discord.png
              description: Join our friendly Discord!
        - Docs:
            - abbr: DO
              href: https://elfhosted.com
              icon: book.png
              description: Documentation         

{{ end }}