---
apiVersion: v2
appVersion: v21.1
description: NZBGet is a Usenet downloader client
name: nzbget
version: 12.4.4
kubeVersion: ">=1.16.0-0"
keywords:
  - nzbget
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/nzbget
icon: https://avatars1.githubusercontent.com/u/3368377?s=400&v=4
sources:
  - https://nzbget.net/
  - https://github.com/k8s-at-home/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: oci://ghcr.io/geek-cookbook/elf-charts
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
