---
apiVersion: v2
appVersion: v22.07.2
description: A dead simple static HOMepage for your servER to keep your services on hand, from a simple yaml configuration file.
icon: https://raw.githubusercontent.com/bastienwirtz/homer/main/public/logo.png
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/homer
name: homer
version: 8.0.2
kubeVersion: ">=1.16.0-0"
sources:
  - https://github.com/bastienwirtz/homer
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: http://chartmuseum.chartmuseum:8080
    version: ~0.2.5
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
