---
apiVersion: v2
appVersion: 4.6.1.0
description: Emby Server is a home media server
name: emby
version: 3.4.2
kubeVersion: ">=1.16.0-0"
keywords:
  - emby
  - jellyfin
  - plex
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/emby
icon: https://truecharts.org/_static/img/emby-icon.png
sources:
  - https://github.com/MediaBrowser
  - https://github.com/k8s-at-home/container-images/tree/main/apps/emby
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
dependencies:
  - name: common
    repository: http://chartmuseum.chartmuseum:8080
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
