{{ if .Values.knightcrawler.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-knightcrawler.elfhosted.com
spec:
  routes:
    - match: Host(`{{ .Release.Name }}-knightcrawler.elfhosted.com`)
      kind: Rule
      services:
        - name: knightcrawler
          kind: Service
          port: 7000
      middlewares:
        - name: chain-hosted-stremio-addon
          namespace: traefik
    - match: Host(`{{ .Release.Name }}-knightcrawler.elfhosted.com`) && PathPrefix(`/configure/`)
      kind: Rule
      services:
        - name: knightcrawler
          kind: Service
          port: 7000
      middlewares:
        - name: {{ .Release.Name }}-traefik-forward-auth
        - name: chain-hosted-stremio-addon
          namespace: traefik
{{ end }}