---
apiVersion: v2
appVersion: 0.43.0
description: Navidrome is an open source web-based music collection server and streamer
name: navidrome
version: 6.4.2
kubeVersion: ">=1.16.0-0"
keywords:
  - navidrome
  - music
  - streaming
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/navidrome
icon: https://github.com/deluan/navidrome/blob/master/ui/src/icons/android-icon-72x72.png?raw=true
sources:
  - https://github.com/deluan/navidrome
  - https://hub.docker.com/r/deluan/navidrome
maintainers:
  - name: auricom
    email: k8s-at-home@xpander.eml.cc
dependencies:
  - name: common
    repository: http://chartmuseum.chartmuseum:8080
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
